<?php
function populate_table($conn)
{
	$tableinsert = 'INSERT INTO users (name, password, role) VALUES ("admin", "admin", 1)';
	mysqli_query($conn, $tableinsert);
	$tableinsert = 'INSERT INTO users (name, password, role) VALUES ("root", "root", 1)';
	mysqli_query($conn, $tableinsert);
	$tableinsert = 'INSERT INTO users (name, password, role) VALUES ("user", "user", 0)';
	mysqli_query($conn, $tableinsert);
	$tableinsert = 'INSERT INTO category (name) VALUES ("phones")';
	mysqli_query($conn, $tableinsert);
	$tableinsert = 'INSERT INTO category (name) VALUES ("laptops")';
	mysqli_query($conn, $tableinsert);
	$tableinsert = 'INSERT INTO category (name) VALUES ("electronics")';
	mysqli_query($conn, $tableinsert);
	$tableinsert = 'INSERT INTO product (name, price, link) VALUES ("Laptop Asus 2018", 940, "http://www.gspremiumstores.com/webshaper/pcm/gallery/lg/e901c415f462580537f372d540c4058a1476179991-lg.png")';
	mysqli_query($conn, $tableinsert);
	$tableinsert = 'INSERT INTO product (name, price, link) VALUES ("Laptop Toshiba AX2102", 1450, "https://4.imimg.com/data4/MI/EX/MY-28174815/toshiba-laptop-500x500.jpg")';
	mysqli_query($conn, $tableinsert);
	$tableinsert = 'INSERT INTO product (name, price, link) VALUES ("Laptop DELL I5", 4790, "http://i.dell.com/sites/imagecontent/products/PublishingImages/xps-15-9560-laptop/laptop-xps-15-pdp-polaris-10.jpg")';
	mysqli_query($conn, $tableinsert);
	$tableinsert = 'INSERT INTO product (name, price, link) VALUES ("Laptop Inspire Axkk2", 2200, "https://images.techhive.com/images/article/2015/08/07-dell-1-100607123-large.jpg")';
	mysqli_query($conn, $tableinsert);
	$tableinsert = 'INSERT INTO product (name, price, link) VALUES ("Laptop Asus I7 2GB RAM, 400GB SSD", 1110, "http://img-us1.asus.com/A/show/AW000706/2017/0802/AM0000001/201708AM020000001_15016211313764650034746.jpg!t500x500")';
	mysqli_query($conn, $tableinsert);
	$tableinsert = 'INSERT INTO product (name, price, link) VALUES ("iHPONE X", 2000, "https://cdn.macrumors.com/article-new/2017/09/iphonexdesign.jpg")';
	mysqli_query($conn, $tableinsert);
	$tableinsert = 'INSERT INTO product (name, price, link) VALUES ("Windows Phone", 1480, "https://www.muywindows.com/wp-content/uploads/2017/07/Windows-Phone-8.1.jpg")';
	mysqli_query($conn, $tableinsert);
	$tableinsert = 'INSERT INTO product (name, price, link) VALUES ("Samsung 450", 1790, "https://s7d2.scene7.com/is/image/SamsungUS/Pdpkeyfeature-sm-g920azdaatt-600x600-C1-062016?$product-details-jpg$")';
	mysqli_query($conn, $tableinsert);
	$tableinsert = 'INSERT INTO product (name, price, link) VALUES ("GSM ALCATEL", 2000, "https://s1.flanco.ro/catalog/product/cache/368/image/1000x1000/9df78eab33525d08d6e5fb8d27136e95/t/5/t56-negru_1.jpg")';
	mysqli_query($conn, $tableinsert);
	$tableinsert = 'INSERT INTO product (name, price, link) VALUES ("Very Good Phone", 100, "http://www.shopcj.com/shopcj/images/productImages/385/micromax-q409-spark-4g-dual-sim-android-mobile-phone-champagne-large_06f9e9a0b561ec9384fb99bed9b586e0.jpg")';
	mysqli_query($conn, $tableinsert);
	$tableinsert = "INSERT INTO cat_prod(idCat, idProd) VALUES (2, 1)";
  	mysqli_query($conn, $tableinsert);
  	$tableinsert = "INSERT INTO cat_prod(idCat, idProd) VALUES (2, 2)";
  	mysqli_query($conn, $tableinsert);
  	$tableinsert = "INSERT INTO cat_prod(idCat, idProd) VALUES (2, 3)";
  	mysqli_query($conn, $tableinsert);
  	$tableinsert = "INSERT INTO cat_prod(idCat, idProd) VALUES (2, 4)";
  	mysqli_query($conn, $tableinsert);
  	$tableinsert = "INSERT INTO cat_prod(idCat, idProd) VALUES (2, 5)";
  	mysqli_query($conn, $tableinsert);
  	$tableinsert = "INSERT INTO cat_prod(idCat, idProd) VALUES (1, 6)";
  	mysqli_query($conn, $tableinsert);
  	$tableinsert = "INSERT INTO cat_prod(idCat, idProd) VALUES (1, 7)";
  	mysqli_query($conn, $tableinsert);
  	$tableinsert = "INSERT INTO cat_prod(idCat, idProd) VALUES (1, 8)";
  	mysqli_query($conn, $tableinsert);
  	$tableinsert = "INSERT INTO cat_prod(idCat, idProd) VALUES (1, 9)";
  	mysqli_query($conn, $tableinsert);
  	$tableinsert = "INSERT INTO cat_prod(idCat, idProd) VALUES (1, 10)";
  	mysqli_query($conn, $tableinsert);
  	$tableinsert = "INSERT INTO cat_prod(idCat, idProd) VALUES (3, 1)";
  	mysqli_query($conn, $tableinsert);
  	$tableinsert = "INSERT INTO cat_prod(idCat, idProd) VALUES (3, 2)";
  	mysqli_query($conn, $tableinsert);
  	$tableinsert = "INSERT INTO cat_prod(idCat, idProd) VALUES (3, 3)";
  	mysqli_query($conn, $tableinsert);
  	$tableinsert = "INSERT INTO cat_prod(idCat, idProd) VALUES (3, 4)";
  	mysqli_query($conn, $tableinsert);
  	$tableinsert = "INSERT INTO cat_prod(idCat, idProd) VALUES (3, 5)";
  	mysqli_query($conn, $tableinsert);
  	$tableinsert = "INSERT INTO cat_prod(idCat, idProd) VALUES (3, 6)";
  	mysqli_query($conn, $tableinsert);
  	$tableinsert = "INSERT INTO cat_prod(idCat, idProd) VALUES (3, 7)";
  	mysqli_query($conn, $tableinsert);
  	$tableinsert = "INSERT INTO cat_prod(idCat, idProd) VALUES (3, 8)";
  	mysqli_query($conn, $tableinsert);
  	$tableinsert = "INSERT INTO cat_prod(idCat, idProd) VALUES (3, 9)";
  	mysqli_query($conn, $tableinsert);
  	$tableinsert = "INSERT INTO cat_prod(idCat, idProd) VALUES (3, 10)";
  	mysqli_query($conn, $tableinsert);
}
?>